### ISSUE TITLE
Bugs in ScaledMonomialSpace2d

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#10]
![image](https://user-images.githubusercontent.com/12275879/74536299-c6e53e80-4f72-11ea-83a3-7bbad8501587.png)

在 `ScaledMonomialSpace2d.py` 中, 如上图中标注的, 
第 194 行应该为 `ldof = self.number_of_local_dofs(p=p)`;
第 205 行, `np.eisum` 应该为 `np.einsum`.

**Comment by weihuayi** [comment]
好的，这个程序我都没有测试过，谢谢。

**Comment by weihuayi** [comment]
其实这个关于基函数的实现还可以改进的，我找到时间会重新实现。

**Comment by weihuayi** [comment]
已经修改了。

**Comment by yoczhang** [comment]
魏老师, 在 `ScaledMonomialSpace2d.py` 中
1. `def mass_matrix(self):` 可以改为 `def mass_matrix(self, p=None):` 的形式吗, 
2. 还需要添加一个计算刚度矩阵的函数 `stiff_matrix(self, p=None)`, 需要组装不同多项式阶数的刚度矩阵.

**Comment by weihuayi** [comment]
好的，我今天就加上去

**Comment by weihuayi** [comment]
我已经加上去了。 我想了一下，我还需要把这个缩放单项式空间重构一下，最近会找时间去做。
