### ISSUE TITLE
HalfEdgeMesh2d.py里面的location函数里有一个x变量未定义

### ISSUE THREAD

**Issue by DoooWeee-byte** [weihuayi/fealpy#102]
![issuse](https://user-images.githubusercontent.com/46317707/175019596-ea618aca-a611-4330-9239-aa412ac0e4c0.PNG)

**Comment by IDCDC** [comment]
测试代码如下：
```
import numpy as np

from fealpy.mesh import MeshFactory as MF
from fealpy.mesh import HalfEdgeMesh2d

box = np.array([0, 1, 0, 1])
mesh = MF.boxmesh2d(box, nx=3, ny=3)
smesh = HalfEdgeMesh2d.from_mesh(mesh, NV=3)

ps = np.array([[0.15, 0.15]])
location = smesh.location(ps)
```
报错原因是因为变量 `x` 没有被定义，我觉得是需要在下述函数第328行中加入 ` x = points[:, 0]`，
https://github.com/weihuayi/fealpy/blob/16582573044f386cde579b87c96510dbf76ab7a6/fealpy/mesh/HalfEdgeMesh2d.py#L324-L343
还需要你进行进一步测试是否为此 bug

**Comment by DoooWeee-byte** [comment]
添加之后上述测试代码可以行得通，但是当p维数为(4, 2)时会有另外的错误出现
![111](https://user-images.githubusercontent.com/46317707/175764739-66303cf7-40e7-4f53-8224-b7f1c2561ed7.png)
