### ISSUE TITLE
Bug in HeatEquationFEM_example.py

### ISSUE THREAD

**Issue by xieweidc** [weihuayi/fealpy#109]
在计算抛物方程的收敛阶时，发现这个算例当中的最后一层误差不会变化。
和陈春雨师兄讨论后，发现是边界条件处理不对。

https://github.com/weihuayi/fealpy/blob/a085c298dabcb2b83e541772b6f0144738485a80/example/HeatEquationFEM_example.py#L107

这样做会使得上一时间层的数值解信息添加到这一时间层当中。

已创建一个 fork 分支，并更新推送了。

**Comment by weihuayi** [comment]
已经合并进来了
