### ISSUE TITLE
mesh.ds.cell_to_edge() 中 keyword 没统一

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#11]
`mesh.ds.cell_to_edge()` 中 keyword 没统一
<img width="896" alt="image" src="https://user-images.githubusercontent.com/12275879/81577873-9c254d80-93dc-11ea-874d-d08558a57938.png">

---

例如 `fealpy/functionspace/NonConformingVirtualElementSpace2d.py -- line 50, cell2edge = mesh.ds.cell_to_edge(sparse=False)` 
如果用 polygonmesh 的话, 会提示 keyword 错误

**Comment by weihuayi** [comment]
我统一了一下, 已经更新到仓库了
