### ISSUE TITLE
Data函数类的建议

### ISSUE THREAD

**Issue by scaomath** [weihuayi/fealpy#125]
## Current 

现在真解函数的类里面，每个类都是独立的。
结果现在初始mesh的时候比较手工，比如在`SinSinData`里面
https://github.com/weihuayi/fealpy/blob/4f4317455c399637d9684b38cdcf0f0f739da036/fealpy/pde/poisson_2d.py#L180-L226

然后`LshapeData`又会来段类似的
https://github.com/weihuayi/fealpy/blob/4f4317455c399637d9684b38cdcf0f0f739da036/fealpy/pde/poisson_2d.py#L755-L799

## Proposal
我觉得可以写一个base class，然后把通用的这些method都归到这个class下面。
特别的函数先继承，这样可以减少重复的code。

比如
```python
class _BaseData:

def __init__(self):
     blah blah blah

def init_mesh(self):
     ...

class Kellogg(_BaseData):

def __init__(self):
    super().__init__()
    blah blah
```

算是个大规模的refactor，thoughts?

**Comment by weihuayi** [comment]
这个建议很好的，可以用来减少代码量。以前写的代码是比较 Case By Case，当时就想着能测试就行了。我一直在想 `init_mesh` 这个功能放在 Data 里是否合适？是不是 Data 最多把 domain 的信息放进来就可以了，用户写自己程序的时候，再调用网格生成的算法来生成网格。我想听听你的建议。

**Comment by weihuayi** [comment]
另外，关于 Data 的组织，特别对于解析形式的模型，实际上可以用 sympy 的生成代码功能，只要给一个 解的表达式，就可以生成直接可以接受 numpy 数组的表达式，这样用户编码的负担就会更轻一点。

**Comment by scaomath** [comment]
> 这个建议很好的，可以用来减少代码量。以前写的代码是比较 Case By Case，当时就想着能测试就行了。我一直在想 `init_mesh` 这个功能放在 Data 里是否合适？是不是 Data 最多把 domain 的信息放进来就可以了，用户写自己程序的时候，再调用网格生成的算法来生成网格。我想听听你的建议。

How about

```python
def default_init_mesh(meshtype: str):
      ...
      return dict(node=node, cell=cell)

class SomeDataFunc(Data):
    def __init__(self):
        super().__init__()

    def init_mesh(self, mesher=None):
        if mesher is None:
            # call the universal default_init_mesh by meshtype
        else:
            # user defined mesher wrapper
```

想法就是用户可以用Fealpy自己的mesher，有external的mesher只需要自己写一个function wrapper输出需要的`node`, `cell`, etc。

**Comment by scaomath** [comment]
> 另外，关于 Data 的组织，特别对于解析形式的模型，实际上可以用 sympy 的生成代码功能，只要给一个 解的表达式，就可以生成直接可以接受 numpy 数组的表达式，这样用户编码的负担就会更轻一点。

这个就非常契合base class的使用，base class里面提供了这个symbolic算导数的方法，然后可以把`evalf()`写成一个wrapper。

**Comment by yoczhang** [comment]
感觉 Fenics 中的方式是很好的参考，可以借鉴
