### ISSUE TITLE
Numpy 数据类型使用

### ISSUE THREAD

**Issue by IDCDC** [weihuayi/fealpy#133]
在运行 example/PoissonFEMWithQuadMesh_example.py 时，报错如下：

![image](https://user-images.githubusercontent.com/82552527/217805992-1c1870d3-dba3-4cc5-b445-1e06acb50773.png)

在查询了官方文档以后，是 numpy 版本更新以后，`np.bool` 被摒弃掉了，转而使用 `np.bool_`. 
再改为 `np.bool_` 以后，程序成功运行

**Comment by weihuayi** [comment]
已经更新了

**Comment by IDCDC** [comment]
老师，现有两个需求。

(1)  在需要使用 fealpy 画网格节点时仍有上述问题，如

https://github.com/weihuayi/fealpy/blob/cc4ee20cd72769b23822156d6a1249214a006233/fealpy/mesh/mesh_tools.py#L33

在这种情况下，是否需要对 fealpy 安装时，加 numpy 版本的限制？

(2) 在服务器上访问 github 要看运气，所以 clone 您的 gitlab 上的仓库，但没有 `np.bool_` 的更新。

**Comment by weihuayi** [comment]
我已经更新了你提出的问题。

**Comment by IDCDC** [comment]
> 我已经更新了你提出的问题。

好的，谢谢老师

**Comment by lalala753** [comment]
`fealpy\fealpy\mesh\StructureQuadMesh.py` 中, 
line 1104, in `boundary_node_flag` 
`isBdPoint = np.zeros((NN,), dtype=np.bool)` 报错, `np.bool` 应该还需要修改为 `np.bool_`.

**Comment by weihuayi** [comment]
我把 FEALPy 中所有 `np.bool` 都替换为 `np.bool_` 啦。
