### ISSUE TITLE
更新fealpy后 打印网格报错

### ISSUE THREAD

**Issue by lalala753** [weihuayi/fealpy#148]
测试代码:
import matplotlib.pyplot as plt
from fealpy.mesh import MeshFactory
mf = MeshFactory
box = [0, 1, 0, 1]
mesh = mf.boxmesh2d(box, nx=1, ny=1, meshtype='tri')
fig = plt.figure()
axes = fig.gca()
mesh.add_plot(axes)
plt.show()

报错类型:
float() argument must be a string or a real number, not 'NoneType'

**Comment by cbtxs** [comment]
这个问题已经处理，如果还是不行可以用
`mesh.add_plot(axes, aspect=1)`
生成网格图像

**Comment by weihuayi** [comment]
@lalala753 请用下面的接口

```
import matplotlib.pyplot as plt
from fealpy.mesh import TriangleMesh

mesh = TriangleMesh.from_unit_square(nx=10, ny=10) 

fig, axes = plt.subplots()
mesh.add_plot(axes)
plt.show()
```
