### ISSUE TITLE
采用统一的安装方式

### ISSUE THREAD

**Issue by zweien** [weihuayi/fealpy#19]
- 建议采用统一的 `setup.py` 文件，直接 `pip install -e .` 的方式安装，我用 github action 对三个平台在 Python3.7 环境下进行了测试。
- 另外建议采用 pytest 进行单元测试，再配合一些 CI 保证多平台多版本的稳定性。

需要的话我可以提交 PR @weihuayi

**Comment by weihuayi** [comment]
非常欢迎啊，你提交一个 PR 吧。&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by weihuayi** [comment]
你的建议非常好，以前因为时间有限，把主要精力都放到代码开发上。单元测试，安装这些环节都没有投入太多精力来做好。我看你在关注 DeepLearning 和 FEM 结合的东西，我们可以找时间聊一聊，为 FEALPy 增加一些 DeepLearning 和 FEM结合的功能模块出来。
