### ISSUE TITLE
圆柱体区域的网格生成

### ISSUE THREAD

**Issue by Baichuan-Sihai** [weihuayi/fealpy#198]
老师您好，想请问如何在圆柱体区域生成四面体网格，比如以单位圆为底面、高为1的圆柱体。

**Comment by wangdong19** [comment]
您好，在TetrahedroMesh中我们添加了一些常用的几何区域生成网格的函数，其中包括生成圆柱体的函数`from_cylinder_gmsh`，您可以通过如下代码进行调用并显示
```python
mesh = TetrahedronMesh.from_cylinder_gmsh(1, 1, 0.1)​
mesh.add_plot(plt)​
plt.show()
```
其中第一个参数为圆柱底面半径，第二个参数为圆柱的高，第三个参数为网格尺寸。您需要更新到最新的FEALPy来使用此函数。

**Comment by Baichuan-Sihai** [comment]
可以使用，谢谢老师！

另外新版numpy删除了np.float，但fealpy中有些地方似乎还未修改，会出现AttributeError，比如fealpy/mesh/mesh_tools.py中的show_mesh_3d函数里面就有一个（第454行，box = np.zeros((2, 3), dtype=np.float）。

**Comment by weihuayi** [comment]
谢谢你的提示，我已经更正了。
