### ISSUE TITLE
Some meshpy installation issue on MacOS mojave 10.14

### ISSUE THREAD

**Issue by scaomath** [weihuayi/fealpy#2]
I think the installation guide for MacOS is quite uncompleted?

Following the guide for Linux, changing the command to `brew` for most packages, I had the following error while installing `meshpy` by running `pip install meshpy`

> ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1

This error can be caused by Xcode being not up-to-date, run `xcode-select --install` will do. Then run `brew config` to make sure CLT has a version.

After installing the CLT of Xcode, go to `/Library/Developer/CommandLineTools/Packages/`, execute the package there `macOS_SDK_headers_for_macOS_10.14.pkg` would add `lstdc++` back to the header.

Now all the `.ipynb` files in doc can be run without an issue.

**Comment by weihuayi** [comment]
Hi, Shuhao, you are right. I need add more install document on MacOS system.  At current, I don't had a mac computer at hand.

**Comment by weihuayi** [comment]
Thanks very much for your test on MacOS.

**Comment by weihuayi** [comment]
Hi, Shuhao, can you write a install instruction in detail for fealpy on macos? Thanks very much.
