### ISSUE TITLE
fealpy中的example一些例子运行有错误

### ISSUE THREAD

**Issue by Smile-In-Heart** [weihuayi/fealpy#25]
LinearElastitcityFEM_example中 m = int(sys.argv[1]) 索引超出范围
OdeTimelineTest中 nupdate = int(sys.argv[1]) 索引超出范围
Poisson_3d_Robin_example中 if sys.argv[1] == 'solve_poisson_robin': 索引超出范围
PoissonAFEMEign中 from petsc4py import PETSc 缺少模块
PoissonFEMWithDirichletBC_example 中 from petsc4py import PETSc缺少模块No module named 'petsc4py'
PoissonFEMWithNeumannBC_example中 p = int(sys.argv[1])索引超出范围

**Comment by weihuayi** [comment]
这些例子需要你输入参数啊。 sys 是用来管理输入参数的

另外， 要用 petsc 的话，也要安装才行, 只是现在在有些平台上安装有问题所以就没有说明 
```
pip install petsc petsc4py
```

**Comment by Smile-In-Heart** [comment]
魏老师，petsc在Anconda上安装不了吗？petsc: this package cannot be built as a wheel  Failed building wheel for petsc 在网上也没有找到安装教程和相对应的whl文件

**Comment by weihuayi** [comment]
你可以把 built 的错误信息贴出来。也许你需要安装 visual studio.

**Comment by Smile-In-Heart** [comment]
![QQ截图20200730200828](https://user-images.githubusercontent.com/65883958/88921273-d34f2080-d2a0-11ea-83ef-8db709ea52aa.png)

**Comment by weihuayi** [comment]
你的 Python 是什么版本的？ 你有没安装 pip install mpi4py ?

**Comment by weihuayi** [comment]
https://stackoverflow.com/questions/61018455/issue-installing-petsc4py-with-anaconda-using-pip-to-indicate-external-petsc-di

**Comment by Smile-In-Heart** [comment]
![QQ截图20200803093801](https://user-images.githubusercontent.com/65883958/89138637-c9fad800-d56e-11ea-9255-05c6b5ffbee3.png)
![QQ截图20200803093858](https://user-images.githubusercontent.com/65883958/89138643-cebf8c00-d56e-11ea-9387-e91cae8f54f1.png)
魏老师，哪个里面的location参数的输入是什么，是matlab的路径吗？

**Comment by weihuayi** [comment]
这里是一个 保存结果的路径， 你输入一下合适的路径就好。
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Smile_In_Heart"; 
发送时间: 2020年8月3日(星期一) 上午9:52
收件人: "weihuayi/fealpy"; 
抄送: "魏华祎"; "Comment"; 
主题: Re: [weihuayi/fealpy] fealpy中的example一些例子运行有错误 (#25)

&nbsp;



 

 
 魏老师，哪个里面的location参数的输入是什么，是matlab的路径吗？
 
&mdash;

**Comment by Smile-In-Heart** [comment]
![QQ截图20200803195837](https://user-images.githubusercontent.com/65883958/89180162-c2b1e980-d5c3-11ea-9eae-423cc75ddd3e.png)
魏老师，我电脑上有matlab但是它却找不到文件或目录

**Comment by weihuayi** [comment]
&nbsp; &nbsp; model = EllipticEignvalueFEMModel(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pde,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; theta=theta,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; maxit=maxit,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; maxdof=3e5,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; step=step,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; n=7,&nbsp; # 初始网格加密次数
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; p=1,&nbsp; # 线性元
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; q=5,&nbsp; # 积分精度
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; resultdir=location,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sigma=100,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; multieigs=False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; matlab=transplant.Matlab(executable='/path/to/matlab')) #这里你写上 matlab 执行文件的路径

&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Smile_In_Heart"; 
发送时间: 2020年8月3日(星期一) 晚上8:00
收件人: "weihuayi/fealpy"; 
抄送: "魏华祎"; "Comment"; 
主题: Re: [weihuayi/fealpy] fealpy中的example一些例子运行有错误 (#25)

&nbsp;



 

 魏老师，我电脑上有matlab但是它却找不到文件或目录
 
&mdash;

**Comment by Smile-In-Heart** [comment]
![QQ截图20200803204526](https://user-images.githubusercontent.com/65883958/89183753-4b338880-d5ca-11ea-9c62-e7ec1e84292c.png)
魏老师，还是不行，是不是因为我使用的windows下双系统Ubuntu系统，而我的matlab本身安装在windows下，它无法找到运行？

**Comment by weihuayi** [comment]
这样是不行的， 你用的是 WSL， 是不能调用 Windows 下的 Matlab 的。你试一下能不能在 WSL 中装一个 Linux 版的 Matlab?&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Smile_In_Heart"; 
发送时间: 2020年8月3日(星期一) 晚上8:47
收件人: "weihuayi/fealpy"; 
抄送: "魏华祎"; "Comment"; 
主题: Re: [weihuayi/fealpy] fealpy中的example一些例子运行有错误 (#25)

&nbsp;



 

 魏老师，还是不行，是不是因为我使用的windows下双系统Ubuntu系统，而我的matlab本身安装在windows下，它无法找到运行？
 
&mdash;

**Comment by scaomath** [comment]
PETSc在Win安装推荐用虚拟机，用Ananconda的virtual env也可以但是dependency容易出问题(就像在Win装其他需要MPI的pkg)。用Fealpy推荐全线换到基于Linux内核的单系统（MacOS也可）有需要用Win虚拟机就好。

**Comment by weihuayi** [comment]
开源软件确实在 Windows 下的兼容性不是有太友好。要做更好的数值计算，确实要用 Linux 或者 MacOS。我也建议你用 Linux 系统。
