### ISSUE TITLE
fealpy.mesh导入问题

### ISSUE THREAD

**Issue by doublehai** [weihuayi/fealpy#260]
魏老师你好，下载了fealpy之后。按照老师给的例子，出现如下错误：
ImportError: cannot import name 'UniformMesh1d' from 'fealpy.mesh'

**Comment by weihuayi** [comment]
你需要提供更多的信息给我，你是什么系统？你是如何安装 FEALPy 的

**Comment by doublehai** [comment]
好的魏老师，我用的windows系统，在pycharm上用的interpreter下载的fealpy。下载之后按照老师给的示例，有些会出错，查看mesh包的目录发现有些包如：UniformMesh1d等在init.py里面没有

**Comment by weihuayi** [comment]
我这边确认一下





------------------ 原始邮件 ------------------
发件人: doublehai ***@***.***&gt;
发送时间: 2023年5月31日 19:47
收件人: weihuayi/fealpy ***@***.***&gt;
抄送: Huayi Wei ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [weihuayi/fealpy] fealpy.mesh导入问题 (Issue #260)





 
好的魏老师，我用的windows系统，在pycharm上用的interpreter下载的fealpy。下载之后按照老师给的示例，有些会出错，查看mesh包的目录发现有些包如：UniformMesh1d等在init.py里面没有

**Comment by nil-is-lin** [comment]
你试一下git clone 到本地后从源码安装，不要pip install -U fealpy。
