### ISSUE TITLE
关于TriangleMesh类中的from_box的一些问题

### ISSUE THREAD

**Issue by redhat123456** [weihuayi/fealpy#264]
首先，我是这样定义我的网格
```
from fealpy.mesh import TriangleMesh

# 定义盒子的边界坐标和网格细分数
x0, x1, y0, y1 = -0.5, 0.5, -0.5, 0.5
nx, ny = 320, 320

# 使用 from_box 方法创建三角网格对象
mesh = TriangleMesh.from_box([x0, x1, y0, y1], nx=nx, ny=ny)

```
很不幸的是报错了，错误是
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[e:\PINN\main.ipynb](file:///E:/PINN/main.ipynb) 单元格 8 in ()
      [5](vscode-notebook-cell:/e%3A/PINN/main.ipynb#X11sZmlsZQ%3D%3D?line=4) nx, ny = 320, 320
      [7](vscode-notebook-cell:/e%3A/PINN/main.ipynb#X11sZmlsZQ%3D%3D?line=6) # 使用 from_box 方法创建三角网格对象
----> [8](vscode-notebook-cell:/e%3A/PINN/main.ipynb#X11sZmlsZQ%3D%3D?line=7) mesh = TriangleMesh.from_box([x0, x1, y0, y1], nx=nx, ny=ny)

AttributeError: type object 'TriangleMesh' has no attribute 'from_box'
```
![image](https://github.com/weihuayi/fealpy/assets/57751257/63774957-dc0b-46d4-b38b-7f0410d2ef22)

但是，我去看了一下TriangleMesh类，发现是有这个'from_box'这个函数，所以我就不懂了，想请教一下大佬

我的fealpy库是通过git clone 然后 pip install . 安装的，所以版本应该是最新，请大佬帮我看一下，让我解决这个小问题😂😂

@weihuayi @zweien @JDevlieghere @scaomath @gitter-badger

**Comment by redhat123456** [comment]
或者教一下我怎么去用😂

**Comment by weihuayi** [comment]
你 clone 的是哪一个仓库？

**Comment by weihuayi** [comment]
你克隆了 fealpy 仓库后，应该在仓库目录下用  `pip install -e .` 来安装 fealpy, 这是一个软安装的方式，本质上是把仓库中的 fealpy 子目录符号链接到系统默认目录下。以后你想更新 fealpy, 只需要在克隆的 fealpy 目录中执行 `git pull` 即可更新到最新版本，但不需要重新安装 fealpy 。有一点必须注意，安装 fealpy 之后，最好不要直接修改本地仓库中的代码，如 `example` 中的代码。如果要修改成自己需要的样子，最好拷贝一份在仓库外修改。

**Comment by weihuayi** [comment]
如果你为 FEALPy 贡献算例或功能，可以联系我。

**Comment by scaomath** [comment]
> 如果要修改成自己需要的样子，最好拷贝一份在仓库外修改。

自己的建议是fork一份，然后把这个仓库设置成upstream:
```bash
$ git remote add upstream https://github.com/weihuayi/fealpy
```
如果用VSCode的话，每次更新选择从upstream pull (rebase)即可。

**Comment by redhat123456** [comment]
感谢各位大佬，问题解决了。ヾ(≧▽≦*)o

**Comment by weihuayi** [comment]
@redhat123456 能否写一个问题解决的总结到这里来？
