### ISSUE TITLE
程序错误invalid literal for int() with base 10: '-f'

### ISSUE THREAD

**Issue by YLN-28** [weihuayi/fealpy#28]
程序：
import sys
import numpy as np
import matplotlib.pyplot as plt

from fealpy.mesh import MeshFactory
from fealpy.functionspace import LagrangeFiniteElementSpace

p=int(sys.argv[1])

mf = MeshFactory()

box=[0,1,0,1]
mesh=mf.boxmesh2d(box,nx=1,ny=1,meshtype='tri')

space=LagrangeFiniteElementSpace(mesh,p=p)

bc=np.array([[1/3,1/3,1/3]],dtype=np.float64)
phi=space.basis(bc)
gphi=space.grad_basis(bc)

print('bc:',bc.shape)
print('phi:',phi.shape)
print('gphi:',gphi.shape)

fig=plt.figure()
axes=fig.gca()
mesh.add_polt(axes)
mesh.find_node(axes,showindex=True)               
mesh.find_cell(axes,showindex=True)
plt.show()

出现错误：
ValueError                                Traceback (most recent call last)
<ipython-input-7-8ad30dee9411> in <module>
      6 from fealpy.functionspace import LagrangeFiniteElementSpace
      7 
----> 8 p=int(sys.argv[1])
      9 
     10 mf = MeshFactory()

ValueError: invalid literal for int() with base 10: '-f'

**Comment by weihuayi** [comment]
这是你输入参数的问题，你的程序名后面应该是的大于 0 的一个整数
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by YLN-28** [comment]
好的，谢谢您！因为我用的是spyder或者jupyter，我发现我将p直接令为3是可以得到结果的，但是让它变成参数的形式仍然不能像您在课程所展示的运行得到结果。我以为是我系统的问题（原本也出了一点问题），一直想重装系统后看是否会得到结果，今天弄好了，发现其他程序都可以了，但是这个问题仍然没有解决🙈，然后问了一下其他同学（Windows系统），貌似也不能得到结果，不知道是否还有其他解决方法呢？



---原始邮件---
发件人: "Huayi Wei"<notifications@github.com&gt;
发送时间: 2020年9月21日(周一) 凌晨5:16
收件人: "weihuayi/fealpy"<fealpy@noreply.github.com&gt;;
抄送: "YLN-28"<1394472505@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [weihuayi/fealpy] 程序错误invalid literal for int() with base 10: '-f' (#28)




 这是你输入参数的问题，你的程序名后面应该是的大于 0 的一个整数 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------

**Comment by YLN-28** [comment]
还有想问一下，这里Linux系统和Windows系统调用参数的有区别么？是否要变换方式？

**Comment by weihuayi** [comment]
没有区别的.
&nbsp;
