### ISSUE TITLE
uh = space.function() # 返回一个有限元函数，初始自由度值是 0？

### ISSUE THREAD

**Issue by YbYang1982** [weihuayi/fealpy#29]
魏老师，你好！space.function 是不是指 $u_h=\phi u=\sum_{i=0}^{N-1}u_i \phi_i$ ? 如果是，基函数\phi在子程序 Function.py 如何体现的？或者如何做到不同有限元基函数都是只要调用 Function.py ，比如Lagrange 元，Nedelec元。

**Comment by weihuayi** [comment]
Function 只是一个接口， 它存储了函数空间做为它的属性， 求有限元函数或梯度值时，本质上是调用函数空间中的 value, grad_value  等函数来求。

**Comment by YbYang1982** [comment]
明白了，谢谢魏老师！
