### ISSUE TITLE
能否规范一下文件名大小写的问题?

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#296]
如果文件内容相同, 是否可以删掉一个, 只保留其中一个?
装系统时没注意, 导致系统不能区分文件名字母的大小写 (可能是我自己系统的问题, 但是实在不想重装系统 -_- ).
1. `/example/oldexample/` 中:
    1. `PoissonFDMWithDirichletBC1D_example.py` 和 `PoissonFDMWithDirichletBC1d_example.py`.
    2. `PoissonFDMWithDirichletBC2D_example.py` 和 `PoissonFDMWithDirichletBC2d_example.py`.
    3. `PoissonFDMWithDirichletBC3D_example.py` 和 `PoissonFDMWithDirichletBC3d_example.py`.
2. `docs/assets/images/mesh/tri-mesh` 中:
    1. `Triangle.png` 和 `triangle.png`.

**Comment by weihuayi** [comment]
我最近也在清理这些代码。你用的是 Win 系统?

**Comment by weihuayi** [comment]
FEALPy 2.0 文件命名约定用小写，类似 poisson_fem_example.py 的形式。我们会尽快清理原来的代码。

**Comment by weihuayi** [comment]
但我还是强烈建议你重装系统。

**Comment by weihuayi** [comment]
你提到问题已经清理了，你再检查一下。后续会继续清理代码

**Comment by yoczhang** [comment]
好的~, 目前用的 mac, 如果重装系统 😂, 我后面注意一下

**Comment by weihuayi** [comment]
无论用什么系统，一个比较保险做法是让自己所有资料都上云，这样换系统、电脑出现意外，都会影响不大。
