### ISSUE TITLE
关于 PolygonMesh 

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#307]
`PolygonMesh` 需要测试和完善. 
1. 例如运行 `fealpy/example/poissionvem_example.py` 就有很多问题.
2. `PolygonMesh` 中去掉了 `edge_normal()` (或者 `edge_unit_normal()`)? 虽然影响不大, 但也算是一个基本数据结构了.
3. `Quadtree.to_pmesh()` 需要导入 `PolygonMesh`.

**Comment by weihuayi** [comment]
这一块代码还在开发测试中，其中 edge tangent normal 的功能移动到了基类里





------------------ 原始邮件 ------------------
发件人: YcZhang ***@***.***&gt;
发送时间: 2023年6月25日 11:48
收件人: weihuayi/fealpy ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [weihuayi/fealpy] 关于 PolygonMesh  (Issue #307)





 
PolygonMesh 需要测试和完善.
  
例如运行 fealpy/example/poissionvem_example.py 就有很多问题. 

PolygonMesh 中去掉了 edge_normal() (或者 edge_unit_normal())? 虽然影响不大, 但也算是一个基本数据结构了. 

Quadtree.to_pmesh() 需要导入 PolygonMesh.

**Comment by yoczhang** [comment]
好的

**Comment by weihuayi** [comment]
Quadtree.to_pmesh() 需要导入 PolygonMesh.   @yoczhang 注意这个功能已经移到了 `polygon_mesh.py` 中， 这样 Quadtree 不需要依赖 PolygonMesh。

**Comment by yoczhang** [comment]
嗯 好的
