### ISSUE TITLE
魏老师你好。假如电脑上有两个版本的fealpy，我想指定使用其中的一个，该怎么设置呢？

### ISSUE THREAD

**Issue by Eizenyz** [weihuayi/fealpy#366]

**Comment by weihuayi** [comment]
需要用到 Python 虚拟环境的功能， 可以参见 https://docs.python.org/zh-cn/3/library/venv.html，把不同的 FEALPy 装在不同的虚拟环境中，就可以了。

**Comment by Xutaodu** [comment]
好的 谢谢老师  我试一下
