### ISSUE TITLE
Ubuntu18安装fealpy失败

### ISSUE THREAD

**Issue by EmilyDuan** [weihuayi/fealpy#4]
按照项目主页Ubuntu相应的install方法进行安装，到第三步“$ sudo -H pip3 install ./”时出错，错误提示为“error: command 'x86_64-linux-gnu-gcc' failed with exit status 1”“Failed building wheel for MeshPy
”。在网上查找许久，尝试多种方法，无果。但又很想使用此包，来进行有限元的学习。
请问老师，有遇到过类似情况，有解决办法么？
谢谢！期待进一步指导～

**Comment by weihuayi** [comment]
你是 Ubutnu 18.04 吗?

**Comment by EmilyDuan** [comment]
> 你是 Ubutnu 18.04 吗?
