### ISSUE TITLE
网格默认画图比例不正确

### ISSUE THREAD

**Issue by weihuayi** [weihuayi/fealpy#423]
@AlbertZyy

请运行
[ https://github.com/weihuayi/fealpy/blob/master/example/fem/hemker_diffusion_convection_lfem_adaptive_2d.py](url)
画出的网格图比例还是不对，网格 x-y 比例应该是 2:1。

![image](https://github.com/weihuayi/fealpy/assets/5236896/ce81e2b9-31ed-4ea2-a70c-a8be2b0611b4)

**Comment by AlbertZyy** [comment]
网格区域为 $[-3, 9]\times[-3, 3]$ ，本身具有比例 2:1。在代码的 115 行，`add_plot`中又指定了参数 `aspect=0.5`，故最终的比例就是 4:1。如果要形成 2:1 的比例，保持 aspect 参数默认就行。

**Comment by weihuayi** [comment]
是的，我没注意到这个地方。
