### ISSUE TITLE
三维网格的可视化

### ISSUE THREAD

**Issue by zhf-0** [weihuayi/fealpy#436]
在调试程序的过程中，需要对三维网格进行可视化处理，方便确定不同单元之间的连接关系，以及单元和面的的编号。以四面体网格为例
```
from fealpy.mesh import TetrahedronMesh
mesh = TetrahedronMesh.from_box([0,1,0,1,0,1], nx=2, ny=2, nz=2)
```
尝试使用以下二维网格中的命令画图
```
fig, axes = plt.subplots()
mesh.add_plot(axes)
```
但是程序报错，无法处理三维网格，而且`TetrahedronMesh`中也没有`add_plot()`函数。

我想请教一下，如何对三维网格进行可视化处理，最好是能够深入到区域内部，还能够高亮显示由部分单元组成子区域，谢谢！

**Comment by AlbertZyy** [comment]
最好能够给出程序报错的信息。另外，你是如何安装 FEALPy 的？因为我无法复现这个错误：执行你给出的代码以后，出错的地方在于四面体网格无法画在 2d 的 Axes 上。改为：
```python
from matplotlib import pyplot as plt
fig = plt.figure()
axes = fig.add_subplot(projection='3d')
mesh.add_plot(axes)
plt.show()
```
以后，可以正常画出图形，如下：
![图片](https://github.com/weihuayi/fealpy/assets/108785827/86facc21-6cee-4931-a55d-64936007cef5)

**Comment by zhf-0** [comment]
谢谢，出错的信息就是你说的`ValueError: Can not plot 3d points in 2d axes`。根据你提供的程序，可以正确地画出三维图形。我想问一下，能否把网格转为`vtk`文件，然后再用`paraview`之类的软件打开，在`paraview`中查看网格信息，比如单元和面的编号

**Comment by weihuayi** [comment]
用这个接口：`mesh.to_vtk(fname='test.vtu')`

**Comment by zhf-0** [comment]
多谢！

**Comment by zhf-0** [comment]
我测试之后发现，生成的`vtu`文件中，好像只包括网格点的坐标和单元节点编号，没有其它信息，类似面的编号，边的编号？

**Comment by weihuayi** [comment]
`mesh.to_vtk(etype='edge', fname='edge.vtu')` 把边输出

**Comment by weihuayi** [comment]
`mesh.to_vtk(etype='face', fanme='face.vtu') ` 输出面

**Comment by weihuayi** [comment]
然后，用 paraview 同时打开三个文件即可

**Comment by zhf-0** [comment]
以下网格
```
mesh = TetrahedronMesh.from_box([0,1,0,1,0,1], nx=2, ny=2, nz=2)
```
单元个数为48，面数为120，边数为98。但是对应的`face.vtu`只包括48个面，部分编号对应不是一个正常的面，而且程序会闪退。对于`edge.vtu`，`paraview`无法打开，只要点击`Apply`就会闪退。

我的系统是`ubuntu 18.04 LST`，通过`apt`下载并安装`paraview`，版本为`5.4.1+dfsg3-1`

**Comment by weihuayi** [comment]
@zhf-0 代码中有一个 bug，已经修正了，你更新一下 fealpy

**Comment by zhf-0** [comment]
我更新了代码，测试了之后发现没有问题，谢谢！
