### ISSUE TITLE
同名文件的大小写问题

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#5]
魏老师，

在当前版本有个小的问题，就是同名文件大小写问题，例如 `fealpy/quadrature/` 下 `Quadrature.py` 和 `quadrature.py` (目前只发现了这个)。而 Git 默认情况下并不区分大小写，这导致我有时候 clone 或直接 download 下来的就只有 `quadrature.py`，并且好像 macOs 默认也不区分大小写，可以参见下面的两个问题描述
[设置 Git 区分文件名大小写](https://blog.csdn.net/youshaoduo/article/details/53184075)
[Mac 上文件名相同、大小写不同的文件夹会合并成一个所导致的问题](https://blog.csdn.net/weixin_33923148/article/details/87987053)

希望魏老师更新一下，另也希望魏老师能更新一下 example.   ^_^

**Comment by weihuayi** [comment]
我把小写的那个文件删除了，那是一个无用的文件。 我在 Linux 下用 Git 是没有大小写的问题，这和 Git 本身的设置有关。 我会抽时间把例子中文件更新一下。 你如果发现问题， 麻烦把出错的信息发给我。 
 
 
------------------ Original ------------------

**Comment by weihuayi** [comment]
或者放到这里来。

**Comment by yoczhang** [comment]
嗯 好的，有少量的我改过了，遇到问题了我再贴过来。
