### ISSUE TITLE
创建一个半边数据结构网格

### ISSUE THREAD

**Issue by xiang-tao** [weihuayi/fealpy#52]
![python-bug](https://user-images.githubusercontent.com/75120277/126060727-be63af5b-fd6a-409c-87e5-bc73283c0f8c.png)
老师，我在看你ppt中关于半边结构数据网格代码时候，运行了前面的两行代码报错了，由于我目前对fealpy的认识很浅薄，所以我不清楚是什么原因造成的，希望得到你的帮助!谢谢老师

**Comment by weihuayi** [comment]
正确的用法是 
```
from fealpy.mesh import MeshFactory as MF
box = [0, 1, 0, 1]
mesh = MF.boxmesh2d(box, nx=10, ny=10, meshtype='tri')
```

**Comment by xiang-tao** [comment]
懂了，谢谢老师！
