### ISSUE TITLE
example.StokesFEM2d_example.py运行的问题

### ISSUE THREAD

**Issue by DoooWeee-byte** [weihuayi/fealpy#56]
魏老师您好，我在运行example中的StokesFEM2d_example.py文件时得到如下结果：
~/fealpy/example$ python3 StokesFEM2d_example.py --degree=2
run boxmesh2d with time: 0.0004553340004349593
The 0-th computation:
run serial_construct_matrix with time: 0.00810586299849092
/usr/lib/python3/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:193: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)
The 1-th computation:
run serial_construct_matrix with time: 0.03071680699940771
The 2-th computation:
run serial_construct_matrix with time: 0.11721844200110354
The 3-th computation:
run serial_construct_matrix with time: 0.458508179999626
[[nan nan nan nan]
 [nan nan nan nan]]

根据报错，可能是组装后的矩阵经过Dirichlet边界处理之后变成了奇异矩阵，请问这是什么原因？

**Comment by weihuayi** [comment]
这个例子还没有调试好
