### ISSUE TITLE
关于HeatEquationAFEM2d_example.py的问题

### ISSUE THREAD

**Issue by DavidDeadpool** [weihuayi/fealpy#61]
魏老师您好！关于fealpy/example/HeatEquationAFEM2d_example.py这一程序，程序中好像没有定义tol这一变量，导致运行时显示：
  File "HeatEquationAFEM2d_example.py", line 79, in <module>
    if err < tol:
NameError: name 'tol' is not defined
谢谢！

**Comment by weihuayi** [comment]
这个程序还没写好, 更新的版本还在修改中. 改完就会上传上来.

**Comment by DavidDeadpool** [comment]
> 这个程序还没写好, 更新的版本还在修改中. 改完就会上传上来.

十分感谢！

**Comment by weihuayi** [comment]
我刚上传一个新的版本, 但运行的结果还不是太好, 还需要进一步的优化.
