### ISSUE TITLE
关于网格粗化的问题

### ISSUE THREAD

**Issue by DavidDeadpool** [weihuayi/fealpy#63]
魏老师您好！关于mesh中的coarsen_triangle_nvb函数，在我的程序（见附件）第123行在调用该函数后竟然把边界的一条边删了，想请教一下老师应该怎么粗化网格，谢谢老师！
由于GitHub的issue无法上传python文件，我只好上传markdown文件，十分抱歉！
[crack.md](https://github.com/weihuayi/fealpy/files/7284138/crack.md)

**Comment by cbtxs** [comment]
这是一个bug，现在已经修改了，更新一下就好了

**Comment by DavidDeadpool** [comment]
老师您好，我已更新，但还是会删除边界（依然是这个程序）

**Comment by DavidDeadpool** [comment]
老师您好，我已更新，但还是会删除边界（依然是这个程序）

**Comment by DavidDeadpool** [comment]
总是在第一次粗化网格的时候就删掉了一条边界，导致后面计算一直有问题

**Comment by weihuayi** [comment]
你的 fealpy 是用开发者模式安装的吗？如果不是的话，是不能调用 fealpy 的更新的，你要重新安装一下
