### ISSUE TITLE
当网格为`quad`时，poisson方程无法正常运行

### ISSUE THREAD

**Issue by zhf-0** [weihuayi/fealpy#68]
在运行示例程序`ConvectinDiffusionReactionFEMwithDirichletBC2d_example.py`时，如果把第`147`行的
```
mesh = MF.boxmesh2d(domain, nx=ns, ny=ns, meshtype='tri')
```
换成
```
mesh = MF.boxmesh2d(domain, nx=ns, ny=ns, meshtype='quad')
```
程序会报错，部分错误信息为
```
File "fealpy/fealpy/mesh/QuadrangleMesh.py", line 60, in integrator
    return GaussLegendreQuadrature(k)
NameError: name 'GaussLegendreQuadrature' is not defined
```
解决的方法很简单，在`fealpy/mesh/QuadrangleMesh.py`的开头加上
```
from ..quadrature import GaussLegendreQuadrature
```

但是运行还是会出错，部分错误信息为
```
  line 155, in <module>
NDof[i] = space.number_of_global_dofs()
  File /fealpy/fealpy/functionspace/LagrangeFiniteElementSpace.py", line 81, in number_of_global_dofs
    return self.dof.number_of_global_dofs()
AttributeError: 'LagrangeFiniteElementSpace' object has no attribute 'dof'
```

换了网格类型后，是不是需要换`functionspace`？哪里出了问题？

**Comment by weihuayi** [comment]
我修改了一下这个例子 `ConvectinDiffusionReactionFEMwithDirichletBC2d_example.py`, 现在三角形和四边形网格都可以工作了. 更一般的空间是 `ParametricLagrangeFiniteElementSpace`, 它适用于 1 至 3 维的各种高阶网格. `QuadrangleMesh` 那是一个 bug, 我也修正了.  `LagrangeFiniteElementSpace` 只适用于单纯型网格.

**Comment by weihuayi** [comment]
另外, 由于 github 访问的问题, 修改的内容暂时还没有推到 github, 你可以在 gitlab 上访问最新的代码.

**Comment by zhf-0** [comment]
好的，谢谢魏老师。
