### ISSUE TITLE
在win10 虚拟子系统linux上运行fealpy/example/oldexample/ 中算例：python3 Poisson.py 时报错： No module named 'fealpy.functionspace.tools'如何解决

### ISSUE THREAD

**Issue by chenzecai** [weihuayi/fealpy#7]
在win10 虚拟子系统linux上运行fealpy/example/oldexample/ 中算例：python3 Poisson.py 时报错： No module named 'fealpy.functionspace.tools'

**Comment by weihuayi** [comment]
请不要用 oldexample 中的例子，那些代码已经不用了。

**Comment by weihuayi** [comment]
很抱歉回复的有点晚，最近太忙了，请见谅。

**Comment by weihuayi** [comment]
现在在 functionspace 模块中已经没有 tools 这个文件了

**Comment by chenzecai** [comment]
多谢魏老师~不过我又试了一下fealpy/example中的算例： python3 PoissonAdaptive.py,然后也有报错： from fealpy.mesh.tree_data_structure import Tritree
ImportError: cannot import name 'Tritree'
将对应的行注释掉后又出现输入问题：p = int(sys.argv[1])
IndexError: list index out of range
不知道魏老师哪可以找到使用文档？

**Comment by weihuayi** [comment]
因为内部程序更新后，有一些例子程序没有及时更新，所以会出问题。你可以看下 doc/fealpycopyright.pdf, 还有 doc/fealpy_ppt.pdf， 先了解一下 fealpy 的设计思想和基本结构。

**Comment by chenzecai** [comment]
好的，多谢魏老师~我先看看~~
