### ISSUE TITLE
关于PoissonWGWithDirichletBC_example.py的问题

### ISSUE THREAD

**Issue by g9002** [weihuayi/fealpy#71]
魏老师您好，在运行这个例子的时候，想使用三角形网格进行WG方法的求解，我将
mesh = MF.boxmesh2d(box, nx=ns, ny=ns, meshtype='poly')中的'poly'改成了'tri'

会出现以下错误：
AttributeError: 'TriangleMeshDataStructure' object has no attribute 'cellLocation'

请问一下，WeakGalerkinSpace2d是否只能使用多边形网格？

**Comment by yoczhang** [comment]
单纯的 `TriangleMeshDataStructure` 为了效率, 其数据结构与 `poly` 的不同, 你可以用 `HalfEdgeMesh2d` 进行转换一下, 例如:
```python
from fealpy.mesh.HalfEdgeMesh2d import HalfEdgeMesh2d
mesh = MF.boxmesh2d(box, nx=ns, ny=ns, meshtype='tri')
mesh = HalfEdgeMesh2d.from_mesh(mesh, NV=3)
```

**Comment by g9002** [comment]
> 

好的，谢谢！
