### ISSUE TITLE
你希望 FEALPy 增加什么样的功能？

### ISSUE THREAD

**Issue by cbtxs** [weihuayi/fealpy#78]
大家对 fealpy 中功能的需求放在这个 issue 下面

**Comment by IDCDC** [comment]
FEALPy 是否能实现嵌套网格？比如一套粗网格，一套细网格采取同一个 mesh 来进行操作，例如
```
mesh.coarse_mesh.entity('node')
mesh.fine_mesh.entity('node')
```

**Comment by cbtxs** [comment]
> FEALPy 是否能实现嵌套网格？比如一套粗网格，一套细网格采取同一个 mesh 来进行操作，例如
> 
> ```
> mesh.coarse_mesh.entity('node')
> mesh.fine_mesh.entity('node')
> ```

fealpy/mesh/下有一个Tritree，就可以做到

**Comment by weihuayi** [comment]
> FEALPy 是否能实现嵌套网格？比如一套粗网格，一套细网格采取同一个 mesh 来进行操作，例如
> 
> ```
> mesh.coarse_mesh.entity('node')
> mesh.fine_mesh.entity('node')
> ```

关键是你这个需求的场景是什么？说明了这个，也许有更好的解决方案。

**Comment by IDCDC** [comment]
> > FEALPy 是否能实现嵌套网格？比如一套粗网格，一套细网格采取同一个 mesh 来进行操作，例如
> > ```
> > mesh.coarse_mesh.entity('node')
> > mesh.fine_mesh.entity('node')
> > ```
> 
> 关键是你这个需求的场景是什么？说明了这个，也许有更好的解决方案。

当前问题是要在细网格上求解多尺度有限元基函数，然后用粗网格上的多尺度有限元基函数来求解控制方程

**Comment by weihuayi** [comment]
> > > FEALPy 是否能实现嵌套网格？比如一套粗网格，一套细网格采取同一个 mesh 来进行操作，例如
> > > ```
> > > mesh.coarse_mesh.entity('node')
> > > mesh.fine_mesh.entity('node')
> > > ```
> > 
> > 
> > 关键是你这个需求的场景是什么？说明了这个，也许有更好的解决方案。
> 
> 当前问题是要在细网格上求解多尺度有限元基函数，然后用粗网格上的多尺度有限元基函数来求解控制方程

两套网格不应该是一个网格对象拥有的功能，这个应该在你有多尺度空间中，拥有两个空间，这样的设计才是对的

**Comment by IDCDC** [comment]
> 

好的老师，我明白了

**Comment by Geniuswangwei** [comment]
FEALPy 是否能实现如下需求的网格: 1) 三角形网格; 2) 三角形的顶点在界面上; 3) 在自适应加密后, 三角形的顶点依然在界面上
![image](https://user-images.githubusercontent.com/71859816/164884881-2c5b43ac-f016-43c5-b029-e05ad20e0a16.png)
