### ISSUE TITLE
fealpy可否生成非凸网格？

### ISSUE THREAD

**Issue by yu-gui-wan** [weihuayi/fealpy#79]
![83c3a6986ae9844cd202d86b09db7bb](https://user-images.githubusercontent.com/68003531/164951403-89e11fa9-f9f5-478a-be40-50c116e00877.jpg)

如上图所示，请问fealpy是否可以生成上图的非凸网格.

**Comment by cbtxs** [comment]
更新到最新的fealpy可以用下面的方法获得这样的非凸网格：
```python
from fealpy.mesh import MeshFactory
mesh = mf.boxmesh2d([0, 1, 0, 1], 10, 8, meshtype='noconvex')
```

**Comment by yu-gui-wan** [comment]
已经完美解决，很迅速，非常感谢。
