### ISSUE TITLE
NameError: name 'threshold' is not defined

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#8]
运行 `PoissonFEMRate.py` 时提示如下错误
```
  File "/Documentsfealpy/functionspace/LagrangeFiniteElementSpace.py", line 86, in boundary_dof
    return self.dof.boundary_dof(threshold=threshold)
NameError: name 'threshold' is not defined
```

**Comment by weihuayi** [comment]
程序还在增加一些更完善的边界条件处理功能，这个错误应该已经解决了。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by weihuayi** [comment]
你重新 更新一下 FEALPy

**Comment by yoczhang** [comment]
好的. 魏老师这几天可不可也更新一下其他算例, 先有一个较稳定的版本, 后面更新时可以以不同的版本号给出. 

另外, 我 python 升级到了 3.8, 给出了一堆 SyntaxWarning, 全部都是关于 `is` 的使用, 如 `if spacetype is 'C':` 中 `is` 更准确的应该为 `==`, 是否可以考虑换成 `==`?

**Comment by weihuayi** [comment]
你的建议很好！我尽快给出一下稳定的版本出来。你能否把 3.8 中遇到的警告信息贴到这里。我看到就修改一下

**Comment by yoczhang** [comment]
3.8 版本的警告如下 
```python
# python3.8
>>> spacetype='C'
>>> spacetype is 'C'
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
True
>>>
```
而在 3.7 版本中没有此类警告
```python
# python3.7
>>> spacetype='C'
>>> spacetype is 'C'
True
>>> 
```
所以在 `LagrangeFiniteElementSpace.py` 的第 22 行开始会有一堆的警告, 不过这类警告只出现在了我首次运行程序的时候, 后面就没出现了.

**Comment by weihuayi** [comment]
好的，以后的程序中我都会改掉的。目前，LagrangeFiniteElementSpace 中接口基本稳定下来了。你在用的过程中有什么意见和想法，欢迎随时和我交流。

**Comment by yoczhang** [comment]
好的.
