### ISSUE TITLE
单元材料属性问题

### ISSUE THREAD

**Issue by lshxx** [weihuayi/fealpy#81]
请问一下，我想要用fealpy做拓扑优化。因此要设置每个网格单元具有不同的弹性模量值，请问有这样的例子或者是实现的办法吗？谢谢！

**Comment by weihuayi** [comment]
这就是在网格上定义一个数据的问题

NC = mesh.number_of_cells()
mesh.cell_data['modulus'] = np.ones(NC)

然后，你就在后续的程序中直接访问这些就可以了
