### ISSUE TITLE
含有两种几何形状的网格

### ISSUE THREAD

**Issue by Geniuswangwei** [weihuayi/fealpy#82]
在电磁波时域有限元计算中, 会用到如下形式网格, 请问FEALPy能实现吗?
![image](https://user-images.githubusercontent.com/71859816/165454509-8d3d1110-30a6-491c-b0d9-fe44720f7e70.png)

**Comment by weihuayi** [comment]
可以实现，直接可以用半边数据结构，也可以重新写一个复合网格类（这个需要一些工作）

**Comment by weihuayi** [comment]
@Geniuswangwei 你的这个网格看起来很怪

**Comment by Geniuswangwei** [comment]
论文里截图的, 可能是不太好看, 可以参看COMSOL的介绍https://cn.comsol.com/support/knowledgebase/1272
![image](https://user-images.githubusercontent.com/71859816/166097091-f30f71c5-49bd-4db9-b7c3-62ec0a7e7bad.png)

**Comment by weihuayi** [comment]
这个完全可以做到，我们要讨论一下，如何更好支持这种带 PML 层的应用

**Comment by Geniuswangwei** [comment]
好的老师
