### ISSUE TITLE
HexahedronMesh 增加 to_vtk 功能

### ISSUE THREAD

**Issue by xieweidc** [weihuayi/fealpy#88]
我想用 Paraview 存储网格的 vtk 数据以达到 3D打印制件动态形成的过程。但此时发现 HexahedronMesh 并无 to_vtk 函数。在仿照 TetrahedronMesh 的 to_vtk 函数时，
https://github.com/weihuayi/fealpy/blob/f6d265586a932d6c4ddf7c644030e954caebce94/fealpy/mesh/TetrahedronMesh.py#L86-L128
遇到以下代码：
https://github.com/weihuayi/fealpy/blob/f6d265586a932d6c4ddf7c644030e954caebce94/fealpy/mesh/TetrahedronMesh.py#L112-L120
这个 cellType 不懂什么意思就不知从何开始了。

**Comment by weihuayi** [comment]
见 fealpy/mesh/vtkCellType.py,  里面定义了 VTK 这个软件包中不同类型单元对应的整数编号， 其中 六面体编号是  12
```
VTK_HEXAHEDRON= 12 
```
