### ISSUE TITLE
可以删掉 fealpy/test/oldtest/ 中一个 test_TriangleMesh.py 吗

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#9]
魏老师, 在 `fealpy/test/oldtest/` 中的有两个文件 `test_TriangleMesh.py` 和 `test_trianglemesh.py`, 这两个文件名大小写不同, 但是我的系统默认不区分大小写, 所以每次 pull 的时时候都提示错误
```
error: Your local changes to the following files would be overwritten by merge:
	test/test_TriangleMesh.py
Please commit your changes or stash them before you merge.
Aborting
```
魏老师可以删掉其中一个文件吗

**Comment by weihuayi** [comment]
我已经去掉了，并推上去了。目前，我正在清理 example 和 test 下面的文件，test 下面的文件将会&nbsp; ClassNameTest.py 命名，主要用于在开发过程上测试相应的类。我也增加了一个 v0.9 的 tag 是没有清理以前的版本， 还增加了一个 v1.0 的开发分支， 这个分支会目前会频繁变动，而 master 分支会保持相对固定，我争取开学前完成 v1.0 版本
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by yoczhang** [comment]
好的
