### ISSUE TITLE
ScaledMonomialSpace2d模块下的 local_projection()函数需要测试

### ISSUE THREAD

**Issue by wuchaohnust** [weihuayi/fealpy#90]
import sys
import argparse
import numpy as np
from fealpy.pde.adi_2d import ADI_2d as PDE
from fealpy.mesh import TriangleMesh
from fealpy.mesh import MeshFactory as mf
from fealpy.functionspace import ScaledMonomialSpace2d

sigma = 3*np.pi
epsilon = 1.0
mu = 1.0
pde = PDE(sigma, epsilon, mu)

##网格
box = [0, 1, 0, 1]
mesh = mf.boxmesh2d(box, nx=2, ny=2, meshtype='tri') 

smspace=ScaledMonomialSpace2d(mesh, p=0)
H0=smspace.local_projection(pde.init_H_value)

**Comment by weihuayi** [comment]
bug 已经修改了，出现原因是以前只测试了多边形网格，没有测试三角形网格
