### ISSUE TITLE
fealpy.mesh.IntervalMesh.bc_to_point() 中的 bug

### ISSUE THREAD

**Issue by yoczhang** [weihuayi/fealpy#97]
`fealpy.mesh.IntervalMesh.bc_to_point()` 中最后的 `einsum` 求和
`p = np.einsum('...j, ijk->...ik', bc, node[cell[index]])`
可以改为 
`p = np.einsum('...j, ij->...i', bc, node[cell[index]])` ?
可以使得返回值 `p.shape` 为 `(NQ, NC)`.

或者改为
`p = np.einsum('...j, ijk->...ik', bc, node[cell[index], None])`?
可以使得返回值 `p.shape` 为 `(NQ, NC, 1)`.

---

重新检查了一下, 
```python
class IntervalMesh():
    def __init__(self, node, cell):
        """

        Parameters
        ----------
        node : numpy.ndarray with shape (NN, 1)
        cell : numpy.ndarray with shape (NC, 2)

        See Also
        --------

        Notes
        -----

        """
        self.node = node
        self.ds = IntervalMeshDataStructure(len(node), cell)
        self.meshtype = 'interval'

        self.nodedata = {}
        self.celldata = {}
        self.edgedata = self.celldata # Notice celldata, edgedata, facedta are  
        self.facedata = self.celldata # same thing.

        self.itype = cell.dtype
        self.ftype = node.dtype
```
`IntervalMesh()` 的 `__init__(node, cell)` 的 `node` 要求 `node : numpy.ndarray with shape (NN, 1)`. 那应该是没问题了. 
不过建议对 `node.ndim` 进行检查, 对于 `node.ndim==1` 的情况进行增加维度处理.

**Comment by weihuayi** [comment]
永超，我增加了数组维度的检查

**Comment by yoczhang** [comment]
好的, 魏老师
